version: '3.8'

services:
  rpa-mit-reference-data:
    build:
      context: .
      target: production
      args:
        - PACKAGE_FEED_URL=${PACKAGE_FEED_URL}
        - PACKAGE_FEED_USERNAME=${PACKAGE_FEED_USERNAME:-PAT}
        - PACKAGE_FEED_PAT=${PACKAGE_FEED_PAT}
    image: rpa-mit-reference-data
    container_name: rpa-mit-reference-data
    environment:
      COMPlus_EnableDiagnostics: 0
      POSTGRES_HOST: ${POSTGRES_HOST:-rpa-mit-reference-data-postgres}
      POSTGRES_DB: rpa_mit_reference_data
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-password}
      POSTGRES_PORT: "5432"
      SCHEMA_DEFAULT: ${POSTGRES_SCHEMA_NAME:-public}
    ports:
      - "5002:5002"