{{- include "ffc-helm-library.container-secret" (list . "rpa-mit-reference-data.container-secret") -}}
{{- define "rpa-mit-reference-data.container-secret" -}}
stringData:
  POSTGRES_USER: {{ .Values.postgresService.postgresUser | quote }}
{{- end -}}